// Centralized product data for use across components
export const productData = [
  {
    id: 1,
    name: "TaylorMade Stealth Driver",
    price: 599.99,
    dealPrice: 499.99,
    category: "Clubs",
    image: "/stealth-driver-closeup.png",
    brand: "TaylorMade",
  },
  {
    id: 2,
    name: "Titleist Pro V1 Golf Balls (Dozen)",
    price: 54.99,
    dealPrice: 49.99,
    category: "Balls",
    image: "/golf-ball-box.png",
    brand: "Titleist",
  },
  {
    id: 3,
    name: "FootJoy Pro SL Golf Shoes",
    price: 169.99,
    dealPrice: 149.99,
    category: "Shoes",
    image: "/footjoy-pro-sl-side-view.png",
    brand: "FootJoy",
  },
  {
    id: 4,
    name: "Callaway Rogue ST Max Irons",
    price: 899.99,
    dealPrice: 799.99,
    category: "Clubs",
    image: "/set-of-golf-irons.png",
    brand: "Callaway",
  },
  {
    id: 5,
    name: "Nike Dri-FIT Golf Polo",
    price: 65.0,
    dealPrice: 55.0,
    category: "Apparels",
    image: "/classic-golf-polo.png",
    brand: "Nike",
  },
  {
    id: 6,
    name: "Ping Hoofer Lite Stand Bag",
    price: 249.99,
    dealPrice: 229.99,
    category: "Bags",
    image: "/colorful-golf-gear.png",
    brand: "Ping",
  },
  {
    id: 7,
    name: "Golf Pride MCC Plus4 Grip",
    price: 11.99,
    dealPrice: 9.99,
    category: "Grips",
    image: "/golfer-interlock-grip.png",
    brand: "Golf Pride",
  },
  {
    id: 8,
    name: "Clicgear 4.0 Push Cart",
    price: 259.99,
    dealPrice: 239.99,
    category: "Trolleys",
    image: "/golfer-push-cart.png",
    brand: "Clicgear",
  },
  {
    id: 9,
    name: "Titleist TSi2 Fairway Wood",
    price: 349.99,
    dealPrice: 299.99,
    category: "Clubs",
    image: "/fairway-wood-closeup.png",
    brand: "Titleist",
  },
  {
    id: 10,
    name: "Adidas Tour360 22 Golf Shoes",
    price: 199.99,
    dealPrice: 179.99,
    category: "Shoes",
    image: "/modern-golf-footwear.png",
    brand: "Adidas",
  },
  {
    id: 11,
    name: "Scotty Cameron Special Select Newport 2 Putter",
    price: 399.99,
    dealPrice: 379.99,
    category: "Clubs",
    image: "/placeholder.svg?height=300&width=300&query=scotty+cameron+putter",
    brand: "Titleist",
  },
  {
    id: 12,
    name: "Bushnell Pro XE Rangefinder",
    price: 549.99,
    dealPrice: 499.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300&query=golf+rangefinder",
    brand: "Bushnell",
  },
  {
    id: 13,
    name: "Callaway Chrome Soft Golf Balls",
    price: 49.99,
    dealPrice: 44.99,
    category: "Balls",
    image: "/placeholder.svg?height=300&width=300&query=callaway+chrome+soft+golf+balls",
    brand: "Callaway",
  },
  {
    id: 14,
    name: "Under Armour Playoff 2.0 Golf Polo",
    price: 65.0,
    dealPrice: 59.99,
    category: "Apparels",
    image: "/placeholder.svg?height=300&width=300&query=under+armour+golf+polo",
    brand: "Under Armour",
  },
  {
    id: 15,
    name: "Cobra KING Forged Tec Irons",
    price: 1199.99,
    dealPrice: 1099.99,
    category: "Clubs",
    image: "/placeholder.svg?height=300&width=300&query=cobra+forged+irons",
    brand: "Cobra",
  },
  {
    id: 16,
    name: "Mizuno JPX921 Forged Irons",
    price: 1299.99,
    dealPrice: 1199.99,
    category: "Clubs",
    image: "/placeholder.svg?height=300&width=300&query=mizuno+jpx921+irons",
    brand: "Mizuno",
  },
  {
    id: 17,
    name: "ECCO BIOM H4 Golf Shoes",
    price: 199.99,
    dealPrice: 179.99,
    category: "Shoes",
    image: "/placeholder.svg?height=300&width=300&query=ecco+golf+shoes",
    brand: "ECCO",
  },
  {
    id: 18,
    name: "Titleist Players 4 Stand Bag",
    price: 219.99,
    dealPrice: 199.99,
    category: "Bags",
    image: "/placeholder.svg?height=300&width=300&query=titleist+golf+bag",
    brand: "Titleist",
  },
  {
    id: 19,
    name: "Callaway Apex Pro Irons",
    price: 1399.99,
    dealPrice: 1299.99,
    category: "Clubs",
    image: "/placeholder.svg?height=300&width=300&query=callaway+apex+pro+irons",
    brand: "Callaway",
  },
  {
    id: 20,
    name: "TaylorMade TP5x Golf Balls",
    price: 49.99,
    dealPrice: 44.99,
    category: "Balls",
    image: "/placeholder.svg?height=300&width=300&query=taylormade+tp5x+golf+balls",
    brand: "TaylorMade",
  },
]
